---
title: Testhumansuits.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
twitter_username: eveevans
github_username: eveevans
owner_name: Erick Vanegas
owner_email: eveevans [at] gmail.com
owner_location: Managua, Nicaragua
bio: 'Co-founder at KakaoMedia.com and TickeTango.com, Web App Developer,  Ruby &
  Open Source enthusiastic.

'
baseurl: ''
url: http://testhumansuits.com
description: 'Blog personal de Erick Vanegas  (a.k.a. @eveevans:  Web App Developer,
  Ruby & Open Source enthusiastic.)  sobre tecnología, Ruby on Rails, Javascript,
  jekyll, AWS,  e-commerce, wordpress.

'
markdown: kramdown
